apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginxpod
  template:
    metadata:
      labels:
        app: nginxpod
    spec:
      containers:
      - image: nginx
        name: nginxpod
