apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-container
        image: my-dockerhub-user/my-flask-app:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: mysql-config
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
        - name: AWS_SECRET_NAME
          value: "aws/rds/instance/tf_rds"   # Secrets Manager의 시크릿 이름
        - name: AWS_REGION
          value: "ap-northeast-2"
